== notmuch vim ==

This is a vim plug-in that provides a fully usable mail client interface,
utilizing the notmuch framework.

image::https://asciinema.org/a/oo4yUOQDDF2CrWZbzhZURFtTW.svg[link="https://asciinema.org/a/oo4yUOQDDF2CrWZbzhZURFtTW"]

== Install ==

You can use any vim plugin manager:

 % git clone https://github.com/felipec/notmuch-vim.git ~/.vim/pack/plugins/start/notmuch-vim

=== vim +ruby ===

Make sure your vim version has ruby support: check for +ruby in 'vim --version'
features.

 % vim --version | grep +ruby

=== ruby bindings ===

Check if you are able to run the following command cleanly:

 % ruby -e "require 'notmuch'"

If you don't see any errors it means it's working and you can go to the next
section, if not, you would need to compile the bindings yourself, or
contact your distribution so they package notmuch correctly.

=== mail gem ===

Since libnotmuch library concentrates on things other than handling mail, we
need a library to do that, and for Ruby the best library for that is called
'mail':

 % gem install mail

This gem is not mandatory, but it's extremely recommended.

== Running ==

Simple:

 % gvim -c ':NotMuch'

You might want to write a wrapper script (e.g. `vnm`)

 #!/bin/sh
 gvim -c ":NotMuch $*"

So you can run:

 vnm is:inbox date:yesterday..

Enjoy ;)

== More stuff ==

As an example to configure a key mapping to add the tag 'to-do' and archive,
this is what I use:

----
let g:notmuch_custom_search_maps = {
	\ 't':		'search_tag("+to-do -inbox")',
	\ }

let g:notmuch_custom_show_maps = {
	\ 't':		'show_tag("+to-do -inbox")',
	\ }
----
